// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBet79HxGHtBvuSOzz5rVpNSf_hk-qEKrY',
    appId: '1:653736608013:web:4b3a011442041d7a6df044',
    messagingSenderId: '653736608013',
    projectId: 'my-amco',
    authDomain: 'my-amco.firebaseapp.com',
    storageBucket: 'my-amco.firebasestorage.app',
    measurementId: 'G-92NMMW7DBM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCbYBzvTJiQJHW6N8TP2SNMj1Y-3ai8Xc',
    appId: '1:653736608013:android:ef3fbd65c49f1a546df044',
    messagingSenderId: '653736608013',
    projectId: 'my-amco',
    storageBucket: 'my-amco.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0pOxgYxl7xw4BqMr9sBbmgzEIZn3IZWc',
    appId: '1:653736608013:ios:c066d697ca994c376df044',
    messagingSenderId: '653736608013',
    projectId: 'my-amco',
    storageBucket: 'my-amco.firebasestorage.app',
    iosBundleId: 'com.app.myamco',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0pOxgYxl7xw4BqMr9sBbmgzEIZn3IZWc',
    appId: '1:653736608013:ios:584dcbc77b129e9e6df044',
    messagingSenderId: '653736608013',
    projectId: 'my-amco',
    storageBucket: 'my-amco.firebasestorage.app',
    iosBundleId: 'com.example.myamco',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBet79HxGHtBvuSOzz5rVpNSf_hk-qEKrY',
    appId: '1:653736608013:web:dc1a774fa7e9241c6df044',
    messagingSenderId: '653736608013',
    projectId: 'my-amco',
    authDomain: 'my-amco.firebaseapp.com',
    storageBucket: 'my-amco.firebasestorage.app',
    measurementId: 'G-Q0XS6E04Q2',
  );
}
